src/objects/PSFileAttachDef__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Extensions__c</fullName>
        <label>Allowed Extensions</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online_Template__c</fullName>
        <label>Online Template</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PSFileAttachTemplate__c</fullName>
        <label>Template</label>
        <referenceTo>PSFileAttachTemplate__c</referenceTo>
        <relationshipLabel>PSFileAttachDef</relationshipLabel>
        <relationshipName>PSFileAttachDef</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upload_Field__c</fullName>
        <inlineHelpText>The API name of Boolean field on object that will be set to True when file has been uploaded</inlineHelpText>
        <label>Upload Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PSFileAttachDef</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSFileAttachDef</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSFileAttachTemplate__c.object
<CustomObject>
    <label>PSFileAttachTemplate</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Template ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSFileAttachTemplate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSFileAttachTemplateController.cls
public class PSFileAttachTemplateController {
      
  @AuraEnabled
  public static List<FileDef> getFileDefs(String templateDefId, String recordId)
  {
      System.debug('getTemplateDef...');

      try {
        List<FileDef> fileDefList = new List<FileDef>();
        for (PSFileAttachDef__c t : [SELECT Id, Filename__c, Allowed_Extensions__c, Help_Text__c, Online_Template__c, 
                                            Required__c, Upload_Field__c
                                       FROM PSFileAttachDef__c 
                                      WHERE PSFileAttachTemplate__c = :templateDefId 
                                      ORDER BY Required__c DESC, Filename__c ASC])
        {
            FileDef fd = new FileDef();
            fd.id = t.id;
            fd.filename = t.Filename__c;
            fd.allowedExtensions = parseExtensions(t.Allowed_Extensions__c);
            fd.helpText = t.Help_Text__c;
            fd.onlineTemplateURL = t.Online_Template__c;
            fd.required = t.Required__c;
            fd.uploadField = t.Upload_Field__c;
            fileDefList.add(fd);
        }

        List<ContentDocumentLink> cdlList = [SELECT Id,  LinkedEntityId, ShareType, SystemModstamp, Visibility, 
                                                    ContentDocument.ContentSize, ContentDocument.FileType, ContentDocument.FileExtension, 
                                                    ContentDocument.Title, ContentDocument.LastModifiedDate, ContentDocument.Id
                                               FROM ContentDocumentLink 
                                              WHERE linkedentityid = :recordId AND IsDeleted=false];

        for (FileDef fd : fileDefList)
        {
            for (ContentDocumentLink cdl : cdlList)
            {
                if (fd.filename == cdl.ContentDocument.Title)
                {
                    fd.uploaded = true;
                    fd.attachId = cdl.ContentDocument.Id;
                    fd.uploadDttm = cdl.ContentDocument.LastModifiedDate.format();
                    fd.uploadSize = cdl.ContentDocument.ContentSize;
                    fd.uploadType = cdl.ContentDocument.FileType;
                }
            }
        }                                      

         return fileDefList;
      } catch (Exception e) {
               throw new AuraHandledException(e.getMessage());
      }
  }

  private static String parseExtensions(String ext)
  {
      String retStr = null;

      if (ext == null || ext.length() == 0)
      {
          return null;
      }
      
      if (ext.contains(','))
      {
          List<String> strList = ext.split(',');
          for (String s : strList)
          {
              s = s.trim();
              if (retStr != null)
              {
                 retStr += ', .' + s.toLowerCase() + ', .' + s.toUpperCase();
              }
              else
              {
                retStr = '.' + s.toLowerCase() + ', .' + s.toUpperCase();
              }
          }
      }
      else {
         ext = ext.trim();
         retStr = '.' + ext.toLowerCase() + ', .' + ext.toUpperCase();
      }
    return retStr;

  }

    public class FileDef
    {
        @AuraEnabled public String id;
        @AuraEnabled public String filename;
        @AuraEnabled public String allowedExtensions;
        @AuraEnabled public String helpText;
        @AuraEnabled public String onlineTemplateURL;
        @AuraEnabled public Boolean required = false;
        @AuraEnabled public String uploadField;

        @AuraEnabled public String attachId;
        @AuraEnabled public Boolean uploaded = false;
        @AuraEnabled public String uploadDttm;
        @AuraEnabled public Integer uploadSize;
        @AuraEnabled public String uploadType;
    }

}